# Generated by Django 2.1.5 on 2019-01-24 07:57

import core.validator
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, null=True, validators=[core.validator.validate_empty_str])),
                ('clusterName', models.CharField(max_length=32, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('delStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, null=True)),
                ('masterName', models.CharField(max_length=16, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('port', models.IntegerField()),
                ('status', models.CharField(max_length=16, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('delStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('port', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=16, null=True)),
                ('clusterCode', models.CharField(max_length=64, null=True)),
                ('delStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, null=True)),
                ('taskName', models.CharField(max_length=16, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('userCode', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(default='stop', max_length=16, null=True)),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRuntime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskCode', models.CharField(max_length=64, null=True)),
                ('masterCode', models.CharField(max_length=64, null=True)),
                ('slaveCode', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, null=True)),
                ('templateName', models.CharField(max_length=16, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, null=True)),
                ('instanceName', models.CharField(max_length=16, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('content', models.TextField()),
                ('userCode', models.CharField(max_length=64, null=True)),
                ('templateCode', models.CharField(max_length=64, null=True)),
                ('parameter', models.TextField(null=True)),
            ],
        ),
    ]
