# Generated by Django 2.1.5 on 2019-04-06 15:20

import core.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_master_clustercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='slave',
            name='password',
            field=models.CharField(max_length=16, null=True, validators=[core.validator.validate_empty_str]),
        ),
        migrations.AddField(
            model_name='slave',
            name='userName',
            field=models.CharField(max_length=16, null=True, validators=[core.validator.validate_empty_str]),
        ),
    ]
