# Generated by Django 2.1.5 on 2019-04-07 15:56

import core.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190406_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, null=True)),
                ('scriptName', models.CharField(max_length=16, null=True, validators=[core.validator.validate_empty_str])),
                ('description', models.CharField(max_length=1000, null=True)),
                ('content', models.TextField(null=True, validators=[core.validator.validate_empty_str])),
                ('userCode', models.CharField(max_length=64, null=True, validators=[core.validator.validate_empty_str])),
            ],
        ),
        migrations.DeleteModel(
            name='TaskRuntime',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='TemplateInstaceParameter',
        ),
        migrations.DeleteModel(
            name='TemplateInstance',
        ),
    ]
