# Generated by Django 2.1.5 on 2019-04-14 14:31

import core.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190408_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='JmeterScriptParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, null=True)),
                ('planName', models.CharField(max_length=24, null=True, validators=[core.validator.validate_empty_str])),
                ('httpSampleName', models.CharField(max_length=24, null=True, validators=[core.validator.validate_empty_str])),
                ('domain', models.CharField(max_length=64, null=True, validators=[core.validator.validate_empty_str])),
                ('port', models.IntegerField()),
                ('path', models.CharField(max_length=64, null=True, validators=[core.validator.validate_empty_str])),
                ('method', models.CharField(max_length=16, null=True, validators=[core.validator.validate_empty_str])),
                ('loopCount', models.IntegerField()),
                ('threadGroupName', models.CharField(max_length=64, null=True, validators=[core.validator.validate_empty_str])),
                ('threadNumber', models.IntegerField()),
                ('rampUp', models.IntegerField()),
                ('scheduler', models.CharField(max_length=16, null=True, validators=[core.validator.validate_empty_str])),
                ('duration', models.IntegerField()),
                ('requestParameter', models.TextField(null=True)),
            ],
        ),
    ]
