# Generated by Django 2.1.5 on 2019-04-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_jmeterscriptparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmeterscriptparameter',
            name='scriptCode',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
