# Generated by Django 2.1.5 on 2019-04-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jmeterscriptparameter_scriptcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jmeterscriptparameter',
            old_name='requestParameter',
            new_name='httpParameter',
        ),
    ]
